services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  app:
    build:
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      - WAIT_HOSTS=mongo:27017
      - WAIT_LOGGER_LEVEL=error
    volumes:
      - ".:/opt/project"
    working_dir: "/opt/project"
